# Site settings
title: Coaching Beacon - Pro Bono Coaching
email: prabhaker.panditi@coachingbeacon.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

#Heading 
Head1: Possibilities Coaching
Head2: Our online pro bono coaching gets results.  
Head3: People report positive changes. Sometimes after just a single session! 
#Head3: Career Growth. Leadership Development. Overcoming Personal Challenges. 
#Head3: â†‘Confidence â†“Stress â†“Sadness â†‘Joy 

#Call to action
USPH: Here's what others say about the results they achieved
#USP:
ğŸ‘‰ğŸ¼ â€œThereâ€™s been a ripple effect of positive things at officeâ€ â€“ A Sr. Corp. Leader
ğŸ‘‰ğŸ¼ â€œI am handling things at the office much more calmlyâ€ â€“ Sr. Software Professional
ğŸ‘‰ğŸ¼â€œI am more assertive. I am also generating more solutions at workâ€ â€“ A Business Person
ğŸ‘‰ğŸ¼ â€œI revived long term relationships and also spent time on my hobby after a long timeâ€ â€“ An IT Consultant

#USPH: How does coaching help you?
#USP: People who receive coaching report improved work performance, better relationships and improved ability to face lifeâ€™s challenges.  Coaching gets these results by tapping deep into your own reservoir of strength. A Coach uses a combination of psychological approaches to match your personality, current state and specific challenges.  The results often seem like magic. You end up uncovering hidden gems of strength. You explore new possibilities. You discover the joy of living. 

#services
ServicesHeading: You should start seeing results from your first session onwards. Otherwise, why get coaching?
#ServicesHeading: At Your Service

Services1H: Leadership Coaching
Services1: As Leadership Coaches, we can help match your unique leadership style to the situation at hand. You then become a more effective leader. You achieve greater results and better stakeholder satisfaction. Our approach is result oriented as we believe that ultimately outcomes matter.

Services2H: Overcoming Career Challenges
Services2: Coaching for career challenges addresses a wide range of issues. These include  ï¿­ leading teams to greatness  ï¿­ improving communication skills  ï¿­ managing stakeholders  ï¿­ working for a promotion  ï¿­ dealing with a difficult colleague or boss  ï¿­ crafting a career strategy  ï¿­ improving assertiveness, etc. 

Services3H: Managing  Personal Issues
Services3: Coaching can help you overcome emotional challenges like  ï¿­ low performance at work  ï¿­ lack of energy and enthusiasm  ï¿­ low self-confidence  ï¿­ low self-esteem  ï¿­ social anxiety  ï¿­ irrational fears  ï¿­ stress  ï¿­ conflict at home or office   ï¿­ poor time management  ï¿­ family issues, etc. 

Services4H: Developing New Skills 
Services4: Coaching can guide you to start developing critical skills, and generate the commitment and focus needed. Such skills may include  ï¿­ speaking in front of a large audience  ï¿­ identifying your strengths  ï¿­ addressing specific weaknesses  ï¿­ focussing on priorities  ï¿­ completing initiatives you start  ï¿­ problem solving ï¿­ dealing with procrastination, etc. 

#Clinets
clinetsH : Our Clients

#Ribbon 
RHead1: Excited about personal growth?
#RHead1: Book your free coaching session
#RHead2: Begin your journey towards new possibilities
#RHead3: â†‘Joy  â†‘Career  â†‘Leadership  â†“Stress
RHead3: Yes, I want to move towards new possibilities in my life and career
RCTA: Request A Free Coaching Session

#ph_number: +91-6362315334
github_username: https://www.linkedin.com/in/prabhakerpanditi/

footer: Â©  2020  www.CoachingBeacon.com

# Build settings
markdown: kramdown
